### DISCUSSION TITLE
dependency override

### DISCUSSION THREAD

**Discussion by cyberprophet** [ShareAnTalk/Kiwoom#33] [General]
```yaml
dependencies:
  flutter:
    sdk: flutter
  kakao_flutter_sdk: ^1.4.2

dependency_overrides:
  pointycastle: 3.7.3  # 원하는 pointycastle 버전 설정
```
